### ISSUE TITLE
Reporte Entrevista

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/actividad-2-entrevista-entrevista-sistemhuerto#2]
Aquí el reporte de entrevista...

**Comment by Yabin-2021** [comment]
[S1GPS 03 - Entrevista.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-entrevista-entrevista-sistemhuerto/files/9470641/S1GPS.03.-.Entrevista.pdf)

**Comment by Ferch0419** [comment]
Excelente trabajo: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
